apiVersion: v1
kind: Service
metadata:
  name: hello-world-stackos-infra-node-4
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: hello-world-stackos-infra-node-4
  sessionAffinity: None
  type: ClusterIP
