name: CI

on:
  push:
    branches: [master, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ################################################################################
  create-image-tag:
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          WITH_V: false

      - id: image-tag
        run: |
          if [ ${{ github.ref }} == 'refs/heads/master' ]; then
            echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
          else
            echo "::set-output name=tag::staging-$(git rev-parse --short HEAD)"
          fi

  ################################################################################
  env-check:
    runs-on: ubuntu-latest
    needs: create-image-tag
    # if: always()

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CHECK ENV
        run: echo "image-tag=${{ needs.create-image-tag.outputs.image-tag }}"

  ################################################################################
  # create-image-tag:
  #   runs-on: ubuntu-latest
  #   needs: create-git-tag
  #   if: |
  #     always() &&
  #     (needs.create-git-tag.result == 'success' || needs.create-git-tag.result == 'skipped')

  #   outputs:
  #     git-tag-master: ${{ steps.image-tag-master.outputs.tag }}
  #     git-tag-staging: ${{ steps.image-tag-staging.outputs.tag }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - if: ${{ github.ref == 'refs/heads/master' }}
  #       run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
  #       id: image-tag-master

  #     # - if: ${{ github.ref == 'refs/heads/staging' }}
  #     - id: image-tag-staging
  #       run: echo "::set-output name=tag::staging-$(git rev-parse --short HEAD)"
