apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: hello-world-stackos-infra-node-4-httpproxy-test
  namespace: test
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: hello-world-stackos-infra-node-4
      port: 80
  virtualhost:
    fqdn: marvel-hello-world.stackos.io
