apiVersion: v1
kind: Service
metadata:
  name: hello-world-stackos-infra-node-4
  namespace: test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: hello-world-stackos-infra-node-4
    app.kubernetes.io/instance: be-api
    app.kubernetes.io/name: hello-world-stackos-infra-node-4
    name: hello-world-stackos-infra-node-4
  sessionAffinity: None
  type: ClusterIP
