name: Docker Image - Staging

on:
  push:
    branches: [staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: patelprashantdds
          password: 84a70041-0816-4b6b-9129-ab859a571c90

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get short commit
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Docker Build & Push for Staging
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: patelprashantdds/hello-world:staging-${{ steps.vars.outputs.sha_short }}
