name: Docker Image - Staging

on:
  push:
    branches: [staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get short commit
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Docker Build & Push for Staging
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:staging-${{ steps.vars.outputs.sha_short }}

  deploy:
    needs: build
    # runs-on: ubuntu-latest

    # steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Get GKE Credentials
        id: get-credentials
        uses: 'google-github-actions/get-gke-credentials@v0.2.1'
        with:
          cluster_name: 'stackos-infra-node-4'
          location: 'us-central1'
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      -name: Get namespaces
       id: get-namespaces
       run: 'kubectl get namespaces'

