name: CI

on:
  push:
    branches: [master, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ################################################################################
  # create-git-tag:
  #   if: github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   # outputs:
  #   #   git-tag: ${{ steps.git-tag.outputs.tag }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Bump version and push tag
  #       uses: anothrNick/github-tag-action@1.36.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  #         WITH_V: false

  #     # - id: git-tag
  #     #   run: echo "::set-output name=git-tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

  ################################################################################
  build:
    runs-on: ubuntu-latest
    # if: ${{ always() && !cancelled() && needs.build.result == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - if: ${{ github.ref == 'refs/heads/master' }}
        uses: anothrNick/github-tag-action@1.36.0
         env:
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
           WITH_V: false

      # - id: image-tag
      #   run: |
      #     # if[[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
      #     #   echo "::set-output name=tag::staging-$(git rev-parse --short HEAD)"
      #     # elif [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
      #     #   echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
      #     # fi
      #     echo "::set-output name=tag::staging-$(git rev-parse --short HEAD)"

  ################################################################################
  env-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CHECK ENV
        run: echo "$(git rev-parse --short HEAD) -> $(git rev-list --tags --max-count=1))"
