name: Docker Image - Staging

on:
  push:
    branches: [staging]

jobs:
  job_id:
    steps:
      - name: 'Auth'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
        credentials_json: '${{ secrets.gcp_credentials }}'

      - name: Get credentials
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'infernos-banzaicloud-k8s'
          location: 'us-central1'

      - name: Get pods
      - id: 'get-pods'
        run: 'kubectl get pods'
