name: CI

on:
  push:
    branches: [master, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-tag-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.step2.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "::set-output name=tag::staging-$(git rev-parse --short HEAD)"

  # create-tag-master:
  #   if: github.ref == 'refs/heads/master'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: '0'

  #     - name: Bump version and push tag
  #       uses: anothrNick/github-tag-action@1.36.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  #         WITH_V: false

  #     -run: echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

  check-envs:
    needs: create-tag-staging
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.create-tag-staging.outputs.tag }}
