name: Docker Image - Staging

on:
  push:
    branches: [staging]

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0.2.1'
        with:
          cluster_name: 'stackos-infra-node-4'
          location: 'us-central1'
          credentials: ${{ secrets.GCP_CREDENTIALS }}
