name: CI

on:
  push:
    branches: [master, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Extract branch name
        # id: branch_name
        # run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # - name: Create Docker Image Tag [staging]
      - if: BRANCH == 'staging'
        run: echo "TAG=staging-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Bump version and push tag for [master]
      - if: BRANCH == 'master'
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          WITH_V: false

      - name: Create Docker Image Tag [master]
        run: echo "TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: ENVS CHECK
        run: echo $BRANCH-$TAG

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build & Push for $BRANCH
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hello-world:$TAG
