name: CI

on:
  push:
    branches: [master, staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ################################################################################
  create-git-tag:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # outputs:
    #   git-tag: ${{ steps.git-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          WITH_V: false

      # - id: git-tag
      #   run: echo "::set-output name=git-tag::$(git describe --tags $(git rev-list --tags --max-count=1))"

  ################################################################################
  create-image-tag:
    runs-on: ubuntu-latest
    needs: create-git-tag
    if: |
      always() && 
      (needs.create-git-tag.result == 'success' || needs.create-git-tag.result == 'skipped') && 
      !(needs.test-1.result == 'skipped')

    outputs:
      git-tag: ${{ steps.image-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
        id: image-tag-master

      - if: ${{ github.ref == 'refs/heads/staging' }}
        run: echo "::set-output name=TAG::staging-$(git rev-parse --short HEAD)"
        id: image-tag-staging

  ################################################################################
  env-check:
    runs-on: ubuntu-latest
    needs: create-image-tag
    if: always()
    # outputs:
    #   tag: ${{ steps.git-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CHECK ENV
        run: echo "${{ steps.create-image-tag.image-tag-staging.outputs.tag }} - ${{ steps.create-image-tag.image-tag-master.outputs.tag }}"
