name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Tag and push current repo code
        run: |
          git tag ${{ github.run_id }}
          git push origin ${{ github.run_id }}
